# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket         = "terraform-state-maxchauo-exercise"
    dynamodb_table = "terraform-state-lock"
    encrypt        = true
    key            = "prod/network/terraform.tfstate"
    profile        = "dev"
    region         = "ap-northeast-1"
  }
}
